title: Recipe Rating Relationship Analysis
description: An exploration of recipe features and their relationship to user ratings.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional: hide GitHub banner (not shown by default in Hacker)
github:
  is_project_page: false

# Optional: hide download button (not typically shown in Hacker)
show_downloads: false



