title: Recipe Rating Relationship Analysis
description: An exploration of recipe features and their relationship to user ratings.
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional: hide GitHub banner (not needed for Merlot, but harmless)
github:
  is_project_page: false

# Optional: hide downloads button if shown
show_downloads: false

